version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env
  db:
    image: mysql:5.6.23
    volumes_from:
      - dbdata
    env_file:
      - env
  dbdata:
    image: alexcheng/data
    volumes:
      - /var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8580:80"
    links:
      - db       
